import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next-Todo-App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="navbar bg-base-300 ">
            <Link href={'/'} className="btn btn-ghost text-xl ">
              Home
            </Link>
          </div>
          <div className="navbar bg-base-300 justify-center text-[25px]">
            <h1 className="underline font-bold">Next.JS Todo</h1>
          </div>
          <div className="navbar bg-base-300 justify-end">
            <Link href={'/about'} className="btn btn-ghost text-xl">
              About
            </Link>
            <Link href={'/report'} className="btn btn-ghost text-xl">
              Report
            </Link>
            <Link href={'/todos-csr'} className="btn btn-ghost text-xl">
              Todos-csr
            </Link>
            <Link href={'/todos-ssr'} className="btn btn-ghost text-xl">
              Todos-ssr
            </Link>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
